<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TableController extends Controller
{
    public function bootstrap_tables()
    {
        return view('bootstrap_tables');
    }

    public function datatable_autofill()
    {
        return view('datatable_autofill');
    }

    public function datatable_buttons()
    {
        return view('datatable_buttons');
    }

    public function datatable_colreorder()
    {
        return view('datatable_colreorder');
    }

    public function datatable_combine()
    {
        return view('datatable_combine');
    }

    public function datatable_default()
    {
        return view('datatable_default');
    }

    public function datatable_fixed_columns()
    {
        return view('datatable_fixed_columns');
    }

    public function datatable_fixed_header()
    {
        return view('datatable_fixed_header');
    }

    public function datatable_keytable()
    {
        return view('datatable_keytable');
    }

    public function datatable_responsive()
    {
        return view('datatable_responsive');
    }

    public function datatable_rowreorder()
    {
        return view('datatable_rowreorder');
    }

    public function datatable_scroller()
    {
        return view('datatable_scroller');
    }

    public function datatable_select()
    {
        return view('datatable_select');
    }

    public function datatable_ajax()
    {
        return view('datatable_ajax');
    }

    public function regular_tables()
    {
        return view('regular_tables');
    }

    public function datatable_ajax_data()
    {
        {
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105087", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            $data['data'][] = array("PNR" => "1605105088", "Name" => "Palani Velayudam", "From" => "<a href=\"#\" class=\"last_seen date_picker\" data-type=\"date\" data-pk=\"1\" data-url=\"/post\" title=\"Select date & time\">15/03/2013 12:45</a>", "To" => "<a href='#' class='username' data-type='text' data-pk='1' data-url='/post' data-title='Enter username'>superuser</a>", "Booktime" => "15/03/2013 13:03", "Exp Drop" => '2626', "Taxi Num" => '<a href="javascript:void(0)" class="select" data-type="select" data-pk="1" data-value="ru" data-url="/post" data-title="Select country">Country</a>', "Action" => '<i class="fa fa-area-chart" aria-hidden="true"></i>');
            print_r(json_encode($data));
            exit;
        }
    }
}
